on: push 

jobs: 
    build: 
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Build index.html file
              run: python build.py


            - name: Upload built files
              uses: actions/upload-pages-artifact@v3
              with: 
                path: out/

    deploy:
        runs-on: ubuntu-latest
        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: build 
        permissions:
            pages: write
            id-token: write
        steps:
            - name: Deploy to GitHub pages
              id: deployment
              uses: actions/deploy-pages@v4
    
    bump:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Bump version and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
        - name: Create a GitHub release
          uses: mathieudutour/release-action@v1
          with:
            tag: ${{ steps.tag_version.outputs.new_tag }}
            name: Release ${{ steps.tag_version.outputs.new_tag }}
            body: ${{ steps.tag_version.outputs.changelog }}